### ISSUE TITLE
Craft visual (Blurry Screen)

### ISSUE THREAD

**Issue by freakzout** [Alphazinn/alpha-craftingV2#3]
When i try to open one of the tables it just stays blurry and do not open the menu can u help me?

**Comment by Alphazinn** [comment]
You probably made a mistake in the config.lua. What error appears in the F8 console when you try to open the table?

**Comment by freakzout** [comment]
theres no error in the F8, i didnt change anything in the config.lua. Can u tell me what line configures the menu graphic part (HTML)

**Comment by Alphazinn** [comment]
https://github.com/Alphazinn/alpha-craftingV2/blob/main/ui/js/script.js#L132

**Comment by freakzout** [comment]
Do you have discord, it would help alot,  we are trying to  configure a server and we love your script

**Comment by Alphazinn** [comment]
Yes, but I'm busy. Reinstall the script and change the parts you want to change one by one and check each time. You will see it working.

**Comment by BlacknGoldy** [comment]
remember folder name should include the V2 or you gonna see it blurry only

**Comment by Alphazinn** [comment]
Update your server artifacts files.
If you are using the old version, use the new version of qbcore.
