### ISSUE TITLE
Multiply item requirements

### ISSUE THREAD

**Issue by favoras** [Alphazinn/alpha-craftingV2#4]
Hello, I have problem with crafting right now. 
Script not checking other requirements to craft, you see I have only 1 Tablet, and I can craft this item. What to do, to fix this?
![image](https://user-images.githubusercontent.com/38849005/196657240-c17b7f01-3095-421e-b5f1-3c18f3535a4c.png)

**Comment by Alphazinn** [comment]
It controls other items as well. The labels and item names of your items may be different. Check them out.

Example:
https://github.com/Alphazinn/alpha-craftingV2/blob/main/config.lua#L98-L99

**Comment by favoras** [comment]
Not working. I can still have only 1 item in inventory (Tablet), and I can craft this item
![image](https://user-images.githubusercontent.com/38849005/196709312-5742d053-402a-4727-84a9-8355bbaa43dd.png)

**Comment by Alphazinn** [comment]
I'll fix asap.

**Comment by Alphazinn** [comment]
I fixed this error. Replace **server/main.lua** and **ui/script.js** files with your old files.
