### ISSUE TITLE
XP for Level 1 to Level 2

### ISSUE THREAD

**Issue by MasterManwah** [Alphazinn/alpha-craftingV2#5]
Hello, not an issue just a question.
How much xp is needed to go from level 1 to level 2?
I'm trying to calculate XP given and XP growth over time/levels.
love the script by the way. thank you

**Comment by Alphazinn** [comment]
100

**Comment by indirectgh** [comment]
it doesnt seem to be 100 xp as im crafting items that give only 5 xp and im getting a level per craft
