### ISSUE TITLE
Problems with vector3

### ISSUE THREAD

**Issue by Syntaxlab-dev** [Alphazinn/alpha-craftingV2#8]
Hi can you Tell me pls what can i change with:

`            Vector3 = vector3(2196.69, 5594.06, 53.76),
            Vector3One = 1.35,
            Vector3Two = 2.2,
            Name = "weaponcrafting", -- Must be same as CraftingStationID
            Heading = 254,
            MinZ = 50.56,
            MaxZ = 54.56,`

Vectore3One/two

**Comment by Alphazinn** [comment]
After you get the location information using polyzone, you can fill in the appropriate blanks.
https://github.com/Alphazinn/alpha-craftingV2/blob/main/config.lua#L64-L73

The 2 number values ​​after **vector3(2196.69, 5594.06, 53.76)** on line 66 are passed as Vector3One and Vector3Two.
